### ISSUE TITLE
Fastlane screenshots broken

### ISSUE THREAD

**Issue by IzzySoft** [sal0max/currencies#1]
Could you please check the screenshots in fastlane? You've added them as symlinks **to local files on your Mac** – that won't work:

    https://github.com/sal0max/currencies/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/screen01.png
    => /Users/maks/dev/android/currencies/art/screenshots/screen01.png

Please replace those symlinks by the real images in your Git tree (and either reverse the symlinks' direction or use hard links instead). Thanks!

**Comment by sal0max** [comment]
Thanks for the hint! Will do.

**Comment by IzzySoft** [comment]
Thanks – looks good now!
