### ISSUE TITLE
[Suggestion] add feature graphic | low-prio

### ISSUE THREAD

**Issue by iNtEgraIR2021** [sal0max/currencies#10]
Hi 👋🏼 

while searching the [`fastlane`](https://github.com/sal0max/currencies/tree/master/fastlane/metadata/android/en-US) directory I couldn't find a feature graphic for this app.

So I just created a (basic) **draft** using GIMP:

![currencies_app_salOmax_feature-graphic](https://user-images.githubusercontent.com/80395360/127138700-345b4275-5cc1-4505-b823-ce114c58c35d.png)

based on the svg images in the [`ic_launcher`](https://github.com/sal0max/currencies/tree/master/art/ic_launcher) directory.

As mentioned above this is just a draft and might not be your liking.

I'll attach my GIMP **.xcf** file. Feel free to modify the image.

📁 [currencies_app_salOmax_feature-graphic.zip](https://github.com/sal0max/currencies/files/6884658/currencies_app_salOmax_feature-graphic.zip)

**Comment by sal0max** [comment]
Good catch.
Implemented in a71645f83845ebd665bf9e97c8c8cfc9606e89cc
