### ISSUE TITLE
[Translations] add more Translations (French, Italian & Spanish)

### ISSUE THREAD

**Issue by iNtEgraIR2021** [sal0max/currencies#11]
Hi 👋🏼 

it's me once again.

## Progress

I just finished **translating**:

|   | French | Italian  | Spanish  |
|---|---|---|---|
| [`strings.xml`](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings.xml)  | X  |  X  |  X |
| [`strings_currencies.xml`](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings_currencies.xml)  |  X  | X  | X   |
| [`string_preference.xml`](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings_preference.xml)  |  X | X  | X  |
| [`README.md`](https://github.com/sal0max/currencies/blob/master/README.md)  |  X | X  |  X |

-> ~~I plan to translate all files listed above very soon.~~ Edit: done
-> I'm open for feedback and contributions.

## Attachments

***Notice** GitHub still does not (seem) to accept `.xml` file uploads so the files have been 'converted' to `.txt`*

[**`strings.xml`**](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings.xml) 
📎 [strings_fr.xml.txt](https://github.com/sal0max/currencies/files/6884938/strings_fr.xml.txt) ✔️ 
📎 [strings_it.xml.txt](https://github.com/sal0max/currencies/files/6884940/strings_it.xml.txt) ✔️ 
📎 [strings_es.xml.txt](https://github.com/sal0max/currencies/files/6884939/strings_es.xml.txt) ✔️ 

[**`string_preference.xml`**](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings_preference.xml)
📎 [strings_preference_fr.xml.txt](https://github.com/sal0max/currencies/files/6884941/strings_preference_fr.xml.txt) ✔️ 
📎 [strings_preference_it.xml.txt](https://github.com/sal0max/currencies/files/6887149/strings_preference_it.xml.txt) ✔️ 
📎 [strings_preference_es.xml.txt](https://github.com/sal0max/currencies/files/6885585/strings_preference_es.xml.txt) ✔️ 

[**`strings_currencies.xml`**](https://github.com/sal0max/currencies/blob/master/app/src/main/res/values/strings_currencies.xml)
📎 [strings_currencies_fr.xml.txt](https://github.com/sal0max/currencies/files/6884942/strings_currencies_fr.xml.txt) ✔️ 
📎 [strings_currencies_it.xml.txt](https://github.com/sal0max/currencies/files/6887193/strings_currencies_it.xml.txt)✔️ 
📎 [strings_currencies_es.xml.txt](https://github.com/sal0max/currencies/files/6887222/strings_currencies_es.xml.txt) ✔️ 

[**`README.md`**](https://github.com/sal0max/currencies/blob/master/README.md)
📎 [README_de.md.txt](https://github.com/sal0max/currencies/files/6931314/README_de.md.txt)
📎 [README_fr.md.txt](https://github.com/sal0max/currencies/files/6931313/README_fr.md.txt)
📎 [README_fr.md.txt](https://github.com/sal0max/currencies/files/6931360/README_fr.md.txt)
📎 [README_it.md.txt](https://github.com/sal0max/currencies/files/6931362/README_it.md.txt)

Edit: ✔️ -> uploaded to [Weblate](https://weblate.bubu1.eu/projects/currencies/)

## live status of Translations @ **weblate**

<a href="https://weblate.bubu1.eu/engage/currencies/">
<img src="https://weblate.bubu1.eu/widgets/currencies/-/multi-auto.svg" alt="Übersetzungsstatus" />
</a>

**Comment by iNtEgraIR2021** [comment]
using weblate (a open source SaaS for translations) might ease the integration and makes it less time consuming.

I used <https://weblate.bubu1.eu> (provided by Marucs Hoffmann) for F-Droid apps before.

**Comment by sal0max** [comment]
That's great work there. Thanks a lot for the participation!
I will look into the topic of community-provided-translations and give a follow-up, soon.

**Comment by iNtEgraIR2021** [comment]
Thank you for kind words.
From my personal point-of-view this issue should increase usability to a significant extend and enable the app to cover possible users in the (majority) of the European countries. Witch should go very well with the ECB as a data source.

**Comment by iNtEgraIR2021** [comment]
**Status**: Now working on [`README.md`](https://github.com/sal0max/currencies/blob/master/README.md).

Please see [above](https://github.com/sal0max/currencies/issues/11#issue-953783599) for details.

**Comment by sal0max** [comment]
Hi @iNtEgraIR2021 
Thanks again for your work. 

I followed your suggestion and created a project on https://weblate.bubu1.eu/projects/currencies/

Would love if you contributed your work to the project. :)

**Comment by iNtEgraIR2021** [comment]
@sal0max 

just finished the upload! Please see [above](https://github.com/sal0max/currencies/issues/11#issue-953783599) for details.

**Comment by sal0max** [comment]
I've found time to merge the translations into the app.
Update will arrive in the stores, soon.
Thank you for your great work, @iNtEgraIR2021 !

I also refactored some string-array resources, so they can be translated.
Hopefully it also makes maintainance easier.

So, you're welcome to translate the rest of the newly added strings if you find the time to do so. :)
Cheers!
