### ISSUE TITLE
[Feature Request] Add two new screens

### ISSUE THREAD

**Issue by ghost** [sal0max/currencies#13]
Thank you for the best currency converter on Google Play and F-Droid! It would be great if you will add two new screens:

1. Screen with all favorite currencies (this is more important).
2. Screen with all currencies.

Currently Currencies app have only screen with one currency.

You can download this converter and copy aforementioned features from it: https://play.google.com/store/apps/details?id=uk.co.currencyconverter&hl=en

**Comment by VasilisKos** [comment]
I think only the screen with the favorite currencies should be added. It'd usefull.

**Comment by sal0max** [comment]
Thanks to the clarification.

As a first step, I will likely add the ability to favorite/star/pin some currencies.
Favorited currencies could be sorted to the top of the picker.
Maybe that will help alone.

As a next step, a new activity like described could be thought about.

**Comment by VasilisKos** [comment]
> Thanks to the clarification.
> 
> As a first step, I will likely add the ability to favorite/star/pin some currencies. Favorited currencies could be sorted to the top of the picker. Maybe that will help alone.
> 
> As a next step, a new activity like described could be thought about.

I've seen a lot of nice, simple apps that fell into the trap of getting more and more complicated, and eventually being spoiled. Let's not fall into that.
The all currencies screen will be literally useless, and won't add anything to the app, but extra size and complexity. One thing that I really liked in the first place in this app was its clear and nice UI, and its straight to the point function.

**Comment by sal0max** [comment]
Some follow-up on this request.

As promised, I added a feature to favorite/star currencies. (Added in version 1.10.0)
I think this probably helps a lot in the described use-case of op.
Maybe this isn't an issue anymore, anyhow, as the account got deleted.

I don't think I will add a screen with more than one target currency.
However, I could imagine a extension of the currency picker, maybe optional via setting.
Something like that (first draft):

![screen_cf2767330738d5dcb144](https://user-images.githubusercontent.com/423373/149179450-b216610f-28ed-4d76-8d32-5e61ecbcccc4.png)

The `€ 1` would adapt to the current input, of course.

Any opinions?

**Comment by VasilisKos** [comment]
Nah... To much useless data downloaded. Might affect app's speed.

**Comment by VasilisKos** [comment]
Ok. But I really don't see any point in this feature.

**Comment by sal0max** [comment]
I decided to solve this request with my idea, anyway.

Initial request in a nutshell was:
>  In my case, I have a relatives and friends in other countries, so very often I need to convert my local currency to some others. [...] Also, there is many countries in the world where people widely using two or more currencies beside their local currency.

Example:
Imagine, the user resides in a country where Euro is used. There are friends in Croatia, Hungary and Romania. Those country's currencies are favorited in the app.
Now one plans to book a nice vacation for all of them. Each participant has to pay € 1150.

All one has to do now, is
1. to enter those € 1150 as base value in the app,
2. open the destination currency picker
3. and active the favorites filter.

![screen1](https://user-images.githubusercontent.com/423373/150684508-36030300-beee-4215-9478-5f1af300f4fd.png) ![screen2](https://user-images.githubusercontent.com/423373/150684102-4cec4599-0eb6-44b8-8781-6ec2638912f1.png)

I'd hope this is a nice compromise, to keep the app simple and lean and also solve this request.

As already mentioned, this is an **opt-in** feature, which has to be activated in the settings.
And also as mentioned: There are **no additional network-requests** done.

This feature will arrive in the next version (1.12.0).

As op is no user here on GitHub any more, I'll close this request as solved.
If there's further discussion about it needed, it can be opened again.
