### ISSUE TITLE
Rates update question

### ISSUE THREAD

**Issue by VasilisKos** [sal0max/currencies#15]
HI, and congrats on this really awesome app, the best of its kind!
I have a little question: are the rates updated everyday on the background or only when the app is launched? I hope the 2nd is happening, which makes sense after all, and saves data.

**Comment by sal0max** [comment]
Thanks for your kind words.

Currencies are not updated in the background.
They are updated only on app start and only when the cached data is older than the current day 0:00 UTC.

see https://github.com/sal0max/currencies/blob/803ee11cad0b310669d24e4d890946d3415a2b1e/app/src/main/java/de/salomax/currencies/viewmodel/main/ExchangeRatesViewModel.kt#L25

You can also manually refresh via the overflow menu in the apps main screen.

**Comment by VasilisKos** [comment]
Thanks for replying! I'm preparing the Greek translation on weblate! 😉
