### ISSUE TITLE
[Feature Request] AMOLED Dark Theme (pure black)

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [sal0max/currencies#16]
Please consider adding an option for a pure black/AMOLED black theme to the app. Thank you!

**Comment by sal0max** [comment]
[XDA did an interesting test a while ago.](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/)
> No, “AMOLED Black” Does NOT Save More Battery Than Dark Gray

I always like to hear some background on a feature request. Why do you wish this feature? Is it because of power consumption? Or aesthetic reasons?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
An AMOLED supporting black theme is easier on the eyes in the dark, and it also looks nicer in my opinion, matching most apps on my phone. I find black themed interfaces easier to navigate with the high contrast between interface elements and the black background.

**Comment by sal0max** [comment]
Thanks for the clarification.

Which version would you prefer? Pure black, or the other one?

![screen_da770f43448384e45365](https://user-images.githubusercontent.com/423373/142502903-cf92eca8-fe01-477a-a0e1-12437724d21f.png) ![screen_b5e7ab9b2fb32694f694](https://user-images.githubusercontent.com/423373/142502904-5df9a0bb-33de-4942-8fd4-88490257d8e4.png)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I wasn't sure at first, but after comparing other apps (such as Simple Mobile Tools), the pure black version is my personal favourite.

**Comment by sal0max** [comment]
Implemented in 9b8cb791b5550d17edbf8cc7d8053eff7ebc63be

Will be included with the next update, soon.

**Comment by sal0max** [comment]
Update is live in Google Play
