### ISSUE TITLE
Translatable app name

### ISSUE THREAD

**Issue by VasilisKos** [sal0max/currencies#17]
I suggest you make the app's title name translatable. It'll be much nicer and convenient to see it in your native language in the app drawer.
A lot of apps, open source or not, follow this. Thanks in advance!

**Comment by sal0max** [comment]
Thanks for the suggestion.

However, I have a different opinion. I don't think it is good practice to translate app names. App names are branding, not just localized identifiers.

Think of Mozilla Firefox. No one would seriously translate it to _Rotfuchs_ (German).
This applies to all kinds of brand names. Imagine heavy metal band Iron Maiden using a localized name in every country. Would be _Eiserne Jungfrau_ in German.
Same happens with human names. It is simply bad style to translate proper names.

I know of some apps using localized names, like the [simple apps](https://www.simplemobiletools.com/) and tbh, but those use mainly identifiers, like _Gallery_, not names like _Awesome Gallery_.

**Comment by VasilisKos** [comment]
I'm aware of your perspective, and totally respect it. It's obviously up to you! 😉👍

**Comment by sal0max** [comment]
Thanks for understanding
