### ISSUE TITLE
Add more currency

### ISSUE THREAD

**Issue by Oymate** [sal0max/currencies#2]
Such as BDT

**Comment by sal0max** [comment]
This is the free API I'm using: https://api.exchangeratesapi.io/latest
Sadly it doesn't provide BDT data.

All other I'm aware of do cost money, which I can't spend with this free app.

Do you know of an API I could use for BDT?

**Comment by Oymate** [comment]
I am thinking if gnome foundation has one, maybe you could take a look?

**Comment by sal0max** [comment]
Thanks for your input.

I could not find an exchange rate API by the GNOME Foundation. Maybe you thought of the data they seem to use in their calculator app? There, they call two external sources:

* The reference rates of the European Central Bank (ECB), just like my app uses.
* And also the International Monetary Fund (IMF) SDR data

See here: https://github.com/linuxmint/gnome-calculator/blob/master/lib/currency.vala

I took the time to compare both data sources. Although the offer a different variety of currencies, BDT doesn't seem to be provided by either one.

So, unless you find a free API for BDT, I don't see a change to add it.

| Currency            | ISO 4217 | [ECB][1] | [IMF][2] |
| ------------------- | -------- | -------- | -------- |
| U.A.E. dirham       | AED      | -        | ✓        |
| Australian dollar   | AUD      | ✓        | ✓        |
| Bulgarian lev       | BGN      | ✓        | -        |
| Brunei dollar       | BND      | -        | ✓        |
| Brazilian real      | BRL      | ✓        | ✓        |
| Botswana pula       | BWP      | -        | ✓        |
| Canadian dollar     | CAD      | ✓        | ✓        |
| Swiss franc         | CHF      | ✓        | ✓        |
| Chilean peso        | CLP      | -        | ✓        |
| Chinese yuan        | CNY      | ✓        | ✓        |
| Colombian peso      | COP      | -        | ✓        |
| Czech koruna        | CZK      | ✓        | ✓        |
| Danish krone        | DKK      | ✓        | ✓        |
| Algerian dinar      | DZD      | -        | ✓        |
| Euro                | EUR      | ✓        | ✓        |
| U.K. pound          | GBP      | ✓        | ✓        |
| Hong Kong dollar    | HKD      | ✓        | -        |
| Croatian kuna       | HRK      | ✓        | -        |
| Hungarian forint    | HUF      | ✓        | -        |
| Indonesian rupiah   | IDR      | ✓        | -        |
| Israeli New Shekel  | ILS      | ✓        | ✓        |
| Indian rupee        | INR      | ✓        | ✓        |
| Icelandic króna     | ISK      | ✓        | -        |
| Japanese yen        | JPY      | ✓        | ✓        |
| Korean won          | KRW      | ✓        | ✓        |
| Kuwaiti dinar       | KWD      | -        | ✓        |
| Mauritian rupee     | MUR      | -        | ✓        |
| Mexican peso        | MXN      | ✓        | ✓        |
| Malaysian ringgit   | MYR      | ✓        | ✓        |
| Norwegian krone     | NOK      | ✓        | ✓        |
| New Zealand dollar  | NZD      | ✓        | ✓        |
| Omani rial          | OMR      | -        | ✓        |
| Peruvian sol        | PEN      | -        | ✓        |
| Philippine peso     | PHP      | ✓        | ✓        |
| Polish zloty        | PLN      | ✓        | ✓        |
| Qatari riyal        | QAR      | -        | ✓        |
| Romanian leu        | RON      | ✓        | -        |
| Russian ruble       | RUB      | ✓        | ✓        |
| Saudi Arabian riyal | SAR      | -        | ✓        |
| Swedish krona       | SEK      | ✓        | ✓        |
| Singapore dollar    | SGD      | ✓        | ✓        |
| Thai baht           | THB      | ✓        | ✓        |
| Turkish lira        | TRY      | ✓        | -        |
| Trinidadian dollar  | TTD      | -        | ✓        |
| U.S. dollar         | USD      | ✓        | ✓        |
| Uruguayan peso      | UYU      | -        | ✓        |
| South African rand  | ZAR      | ✓        | ✓        |


[1]: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
[2]: https://www.imf.org/external/np/fin/data/rms_five.aspx

**Comment by Oymate** [comment]
Hmm, I will keep searching then :)

**Comment by sal0max** [comment]
I've added a bunch of currencies with 56e8cdcb1d81e655b150e2df32d67fafe4b0345e

**Comment by sal0max** [comment]
BDT added with https://github.com/sal0max/currencies/commit/662132e641ddbbcd89109edb542454d72613cbc9
Now offering 162 currencies. 🙂
