### ISSUE TITLE
Swipe down to update rates

### ISSUE THREAD

**Issue by VasilisKos** [sal0max/currencies#20]
I think swiping down the main app screen, to update the currency rates would be a very convenient feature. How about adding it? 😊

P. S. Have a happy new year! 🎉🍾🥂🎅

**Comment by sal0max** [comment]
Happ new year!

Could be done, yes. Thanks for the idea.
Will consider adding it in the next release.

**Comment by sal0max** [comment]
Included in [1.11.0](https://github.com/sal0max/currencies/releases/tag/1.11.0)
