### ISSUE TITLE
Problem with fer.ee?

### ISSUE THREAD

**Issue by VasilisKos** [sal0max/currencies#21]
I noticed that when the fer.ee provider is selected there's an issue. While in the main screen the rates are of yesterday's, in the graph screen today's rates appear. I don't know if that's a problem of the app or the provider, but it should be fixed.

**Comment by sal0max** [comment]
Good catch!

There was an error in the implementation. When fer.ee was selected, it was only used for the current rates. Timeline was still fetched from exchangerate.host.
I noticed it some days ago myself and already pushed a fix: 1ef40e57781e1a3dc7d2d893df16896b1914940b

Will be included in the next release.

**Comment by VasilisKos** [comment]
In today's update there seems to be another bug concerning the providers. If you change provider, the main screen rate isn't updated. But if you go to the graph page it is updated. You have to exit the app and start it again to get the current provider rates. Changing the provider gives the problem again...

**Comment by sal0max** [comment]
I've noticed that behavior myself 1 or 2 times, but can't seem to reproduce it reliably.

**Comment by sal0max** [comment]
Can confirm, that was an issue.
Fixed it in the progress of a greater refactoring: 01ac14aaa1ad2b23d5d4980a47c993d8f7d67633

Will be included in the next release,
