### ISSUE TITLE
[Translation Contribution Request] Can you add the following languages?

### ISSUE THREAD

**Issue by SecularSteve** [sal0max/currencies#24]
The missing languages in the Weblate that I'm proficient in are **Dutch** and **Bosnian**.

**English** and **German** are already included (and finished), and if it's possible, you could include **Serbian** and **Croatian** (because Bosnian is essentially the same as them, but with very minor dialect differences).

**Comment by sal0max** [comment]
Hi, thanks for taking interest in this project.

If you want provide translations, you can add them yourself in Weblate. Just click [on the component you want to translate](https://weblate.bubu1.eu/projects/currencies/#components) first and select `start new translation`, at the bottom.

MainActivity, SettingsActivity and TimelineActivity would be most important to translate, as Currency names can be quickly exported from Wikipedia.

**Comment by SecularSteve** [comment]
okay, thank you
