### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by sedrubal** [sal0max/currencies#25]
Thanks for the great app.

It would be great to add a feature to convert currencies with historic transfer rates. This could be done by adding a datetime picker to the main screen. What do you think about it?

**Comment by sal0max** [comment]
Good idea. The API providers currently in use all seem to provide that data:

* Exchangerate.host:
  https://api.exchangerate.host/2020-04-04
* Frankfurter.app:
  https://api.frankfurter.app/2020-04-04
* Fer.ee:
  https://api.fer.ee/2020-04-04

Have to think about what earliest date to allow/to find out which earliest date is available.
* For Exchangerate.host currently 1999-02-01, but with a [limited data set](https://api.exchangerate.host/1999-02-01).
* Frankfurter works back until [1999-01-04](https://api.frankfurter.app/1999-01-04).
Could be variable, however.

Also have to think about a caching strategy, as the current one won't probably work any more.

Thanks for the suggestion! 👍

**Comment by sedrubal** [comment]
Great! For better motivation I can tell my use case: for a longer stay in a country with a foreign currency, I have to convert the amount of bills regularly into the currency of my home country for refund of my financial baker. Therefore I need the transfer rates of the dates of the transactions which might be some days in the past.

**Comment by sal0max** [comment]
This feature was implemented in 8142ae61e576eb94a5a59cdad5468212d20926cb and got released in [1.16.0](https://github.com/sal0max/currencies/releases/tag/1.16.0). Will arrive in the app stores, soon.
