### ISSUE TITLE
System preferences dark nicht theme isn't working

### ISSUE THREAD

**Issue by amarradi** [sal0max/currencies#26]
I have changed my android system to the dark look. In the currencies app, I have set the system settings to load. Unfortunately, the app remains light and does not go dark

![Screenshot_20220412-153350.png](https://user-images.githubusercontent.com/720573/162974380-035ff601-7ecf-4d90-8b4e-bcef11ec868d.png)

**Comment by amarradi** [comment]
That is really strange. When I set the darkmode it runs. I use a motorola
g6 plus with android 9 and I use the app with version 1.15.0. I came up
with this because I wanted to implement this functionality in my own app
and first looked at my installed apps to see how they do it. I have tested
two or three apps but so really error-free runs none. A bug in Android 9?
If i set light as systemstandard threema for example changed the theme but
not in the other way.
Mein Krebstagebuch unter https://www.marcusradisch.de


Am Di., 12. Apr. 2022 um 18:22 Uhr schrieb sal0max ***@***.***

**Comment by sal0max** [comment]
_Real_ dark/light theme support only exists since Android 10, according to the [Android documentation](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme).
> Dark theme is available in Android 10 (API level 29) and higher. It has many benefits: [...]

So, maybe the dark theme in your Motorola G6 is more of a proprietary vendor implementation, which probably changes mainly the system apps. However, according to e.g. [this article](https://www.theverge.com/2019/3/22/18270975/how-to-dark-mode-iphone-android-mac-windows-xbox-ps4-nintendo-switch), you can try enabling it in the developer options on Android 9.
> If your phone runs Android 9 Pie, you can set Night Mode to remain on at all times, but you have to have Developer options (which give you access to some extra features) enabled first.
> - To enable Developer options, open up Settings, then tap on “About phone.”
> - At the very bottom of this screen, you’ll see “Build number.” Tap that seven times. This will give you access to the Developer options, which you can then find in Settings by going to System > Advanced > Developer options.
> - Scroll down until you see Night Mode near the bottom of the first section of the menu. You can set it to “Always on” or “Automatic (based on time of day).”

**Comment by amarradi** [comment]
Yes i found also this information. It's no bug it's a feature. Its maybe
time to update my hardware. Sorry for the stress

sal0max ***@***.***> schrieb am Mi., 13. Apr. 2022, 00:32:

**Comment by amarradi** [comment]
Yes I know but I take a lot of pictures with the phone and I've heard the
lineage OS camera is not that good. So I have to decide what I need

sal0max ***@***.***> schrieb am Mi., 13. Apr. 2022, 09:32:

**Comment by sal0max** [comment]
Not trying to persuade you, just my experience with LineageOS on OnePlus 3T and OnePlus 8: After installing GCam, the images were even better than with the proprietary camera apps in the stock firmware.

🙂
