### ISSUE TITLE
[feature request] shorthand for multiple zeroes

### ISSUE THREAD

**Issue by gotiniens** [sal0max/currencies#29]
In Indonesia most prices are multiples of 1000. A button to aromatically add 3 zeroes, or a feature to always assume 3 zeroes would be handy when comparing prices op products

**Comment by sal0max** [comment]
I can see your point. There exist calculators with additional `00` and `000` buttons.
I will think of something to solve this issue. 👍

**Comment by sal0max** [comment]
I came up with following solution.

In the next release you will be able to enable a _extended keyboard layout_ in the app settings. It will look like this:

![screen_5fcc41a964b3eea7b6e0](https://user-images.githubusercontent.com/423373/175809186-d0810566-b585-4a5e-83a0-2af62c7f8304.png)

Is that a solution you're agreeing with, @gotiniens?

If yes, you can help translating the new setting to Indonesian:
- title: https://weblate.bubu1.eu/translate/currencies/android-app-preferences/id/?checksum=5e838f68eec79733
- description: https://weblate.bubu1.eu/translate/currencies/android-app-preferences/id/?checksum=e86b908695578dac

Or if it's more convenient for you, just provide it here and I'll add it.
- title: `Extended Keypad`
- description: `Add two additional buttons: <b>00</b>&nbsp;and&nbsp;<b>000</b>.`

**Comment by gotiniens** [comment]
It looks great, This would have made it a lot easier.

I'm not Indonesian though so I can not translate to Indonesian, I was traveling the country. I added suggestions for my native language.

**Comment by sal0max** [comment]
Great, thanks a lot!
