### ISSUE TITLE
Allow pasting numbers from clipboard

### ISSUE THREAD

**Issue by mayhair** [sal0max/currencies#31]
This would make the app much more convenient. I am tired of going back and forth between a document and this app just to enter a price with not a lot of zeroes (for example, 1,949.50).

**Comment by sal0max** [comment]
Great idea. Will considerate implementing that.

**Comment by sal0max** [comment]
Added support for number pasting. Just long click on the "from" value and paste from the clipboard.
Will be included in the next release.

![screen_6329ee32a06fa6bcc346](https://user-images.githubusercontent.com/423373/184665147-6ff9a5fb-5335-4198-8cf7-45ae79ccbb98.png)

**Comment by sal0max** [comment]
[1.17.2 released](https://github.com/sal0max/currencies/releases/tag/1.17.2). Should arrive in the app stores, soon.
