### ISSUE TITLE
HTTP 521 error

### ISSUE THREAD

**Issue by KB8DOA** [sal0max/currencies#34]
I am finding that this app is not working.
Am getting HTTP 521 Error

**Comment by sal0max** [comment]
> 521: Web Server Is Down
> The origin server refused connections from Cloudflare. Security solutions at the origin may be blocking legitimate connections from certain Cloudflare IP addresses.

This error code indicates that there is a server-side error. This app uses 3rd-party APIs for aggregating exchange rates. So, nothing I can do about it. However, maybe this helps if it happens again in the future:

1. Switch to a different API provider in the app settings.
2. Mostly those are temporary outages. So waiting for 1-2 hours usually fixes the problem. To speed up the process, you can file issues at the API providers:
   
   - exchangerate.host: https://github.com/Formicka/exchangerate.host/issues/
   - frankfurter.app: https://github.com/hakanensari/frankfurter/issues
   - fer.ee: https://github.com/narorolib/fer/issues
   
   First check in the app settings, which one is selected.

**Comment by sal0max** [comment]
related: https://github.com/Formicka/exchangerate.host/issues/174
