### ISSUE TITLE
Croatian language doesn't show up in the language picker

### ISSUE THREAD

**Issue by biuklija** [sal0max/currencies#40]
Croatian doesn't show up in the language picker in 1.18.1, regardless of the system language. Croatian, however, works when Croatian is the system default language.

**Comment by sal0max** [comment]
Thanks for reporting this issue. I noticed it too, yesterday.
Fix: https://github.com/sal0max/currencies/commit/8404290e01699fc3c3f8085b27e1d37150ce78b4

Will be included in the next release.

👍
