### ISSUE TITLE
Display the currency symbol before or after the amount, depending on language

### ISSUE THREAD

**Issue by biuklija** [sal0max/currencies#41]
In many languages, the currency symbol or the ISO code follow the amount, not precede it, i.e. `23,1 €` or `1$`, more information [here](https://qr.ae/prAxpx). Additionally, Croatian has a whitespace before the symbol.
Would it be possible to implement this on the main screen, the same way decimal point and separator are handled in the translation?

**Comment by sal0max** [comment]
Thanks for bringing this up. Definitely something I can imagine.
Will try it out a bit how it feels.

**Comment by sal0max** [comment]
Update: Has been [quite some work](https://github.com/sal0max/currencies/commit/583ccdc2f61ce35e35b5e6d35057146b34802a7f). Much more than anticipated, to be honest.  
But much worth the effort.   

Changes will be included in the next release.
