### ISSUE TITLE
[change] Don't localize Language names

### ISSUE THREAD

**Issue by Mart-Bogdan** [sal0max/currencies#42]
Currently application settings language selection shows language names localized to currently active language.

In my opinion this doesn't make sense, and is actually harmful.

Consider following scenario:

1. User changed language by accident to some lang that they don't know.
2. They want to switch back
3. But language list is in foreign language and all language name are translated.

It would be really hard to select language in this case. And it would be hard to even fine English (as most common denominator) becouse it is also translated. Even worse if selected language is not using Latin charset. Then it woun't be possible to read even, if that's not language you know.

So my proposal is to display language list same way on each locale, so don't localize it.

Show language as native lang name + english lang name. For example `Arabic (العربية)` 

This would be more useful. And actually what's the sense to show, say Polish language name in Arabic?

**Comment by sal0max** [comment]
First, thanks a lot for helping to localize this app to Ukrainian. Sláva Ukrayíni! 🇺🇦

Regarding your issue:
I completely agree, that it is a tough case, localizing a language picker or not. Let me explain my thoughts.

![Screenshot_1674769016](https://user-images.githubusercontent.com/423373/214956514-b729652a-bf88-4e8c-8578-eca1cb9453d7.png)

As you can see in above screenshot, all languages are listed in two locales:
\<Language name in the native language>
\<Language name in the currently selected language>

The idea is, that a user can have a look at the language list and might be interested what languages are supported. He might find it tough to decipher or even distinguish between `українська мова` (Ukrainian) and `Български` (Bulgarian), if he only knows Latin letters. The second row will explain it.



Of course this does only apply to the picker, as once a language is selected, there's only all-localized left:
![Screenshot_1674769841](https://user-images.githubusercontent.com/423373/214958703-b30309d8-1275-4771-bca7-f70576ae252f.png)

But, to be fair, this is the exact same behavior as in the Android system settings:
![Screenshot_1674770084](https://user-images.githubusercontent.com/423373/214959497-ebdf35e9-f6f3-4f4a-ae6f-81a782804d55.png)

As this is a tough topic, I decided to stick to the same system as the big players. Besides the Android system settings, there are some popular apps, where users can select a custom language. And each of those behaves the exact same way as Currencies does (native + localized in the picker & localized once selected). You can check for yourself:
- WhatsApp
- Signal
- Telegram
- Instagram
- Firefox
- ...

I don't think it is a good idea to break with a what seems de-facto standard.

Nevertheless, thanks a lot for your input. Please raise other things, you might discover.

Of course I'm open to further discussion on this topic. However I find it hard to imagine that all those big companies didn't do their research and all those bright people working there didn't spend enough time thinking about this setting.

**Comment by Mart-Bogdan** [comment]
Oh. I see now. That actually makes sense.

To be honest, my bad. I haven't looked at this settings view properly, and created issue rushing. To be honest, I've just picked first not big project on translate.codeberg, but my bad that I didn't bother to open settings and check it. Sorry for that. I didn't realized that you already display it in two languages. I thought it would be displayed only in loclaized to current lang.

But my second thought is, perhaps adding icon to language picker?
![image](https://user-images.githubusercontent.com/775038/215272440-cc785c2d-7b5f-473c-b8a6-295ec1edcb4e.png)

https://www.flaticon.com/free-icon/language_484633?term=language&page=1&position=2&origin=tag&related_id=484633
icon is free, but requires attribution:

 > Paste this link on the website where your app is available for download or in the description section of the platform or marketplace you’re using. `<a href="https://www.flaticon.com/free-icons/language" title="language icons">Language icons created by Freepik - Flaticon</a>`

If so, I guess that different Issue.


**P.S.** Thanks for accepting my translation, I haven't finished everything in settings view. Would try to address it today. 

Thanks for such detailed reply. Now I'm thinking myself so I've took to many of your time.

**Comment by sal0max** [comment]
No need to say sorry. I'm happy about everyone who is participating in this project. Constructive feedback is always welcome.

I like your idea with the icon. I'll look into that.
I'd pick one of the Material icons, though, as they provide consistent look with the Android platform and are even usable without attribution. For future reference: https://fonts.google.com/icons?icon.query=language
