### ISSUE TITLE
Refresh Rates: error message covers bottom row

### ISSUE THREAD

**Issue by kojid0** [sal0max/currencies#45]
<img alt="Screenshot" src="https://user-images.githubusercontent.com/24477557/217547174-7329155e-0175-4e64-8cbc-d1981f541adf.png" height="800" />

**Comment by sal0max** [comment]
Yes, the bottom is the standard position of a [Snackbar](https://m3.material.io/components/snackbar/guidelines).
The [Material 3 documentation states](https://m3.material.io/components/snackbar/guidelines#fdd21616-a476-4299-84f2-7e963919eded):
> Snackbars should be placed at the bottom of a UI, in front of app content. Avoid placing a snackbar in front of frequently used touch targets or navigation.

So, that's a tough one in this app. It's either in front of touch targets or not at the bottom any more.

Where do you suggest should it be placed instead?

**Comment by kojid0** [comment]
What do you think about placing it where the refresh state is being placed?
![Screenshot1](https://user-images.githubusercontent.com/24477557/217685814-0a402bb3-2241-4a3a-bf4f-0ebbf60a5c1b.png)

**Comment by sal0max** [comment]
Would look like this:
![Screenshot_1675905170](https://user-images.githubusercontent.com/423373/217689376-660b5a32-271b-4f56-ade2-bca08017af8e.png)

Feels strange to me. But you also have a valid point that blocking the keypad is an issue.
I have to think about this.

**Comment by sal0max** [comment]
Thanks for opening this issue, @kojid0 
Implemented as shown in that last screenshot. Took a little time getting used to it, but I like it, now!

Will come in the next release.
