### ISSUE TITLE
[Feature Request] Self Define Rate

### ISSUE THREAD

**Issue by gthbusrr** [sal0max/currencies#5]
First of all, GREAT APP and Great Simple Design, thank you so much.

It would be great if a feature to define the conversion rate myself and lock it to prevent it from updating. This could serve two proposes:

1. Allow conversion based on purchasing rate of the foreign exchange.
2. Allow custom currencies such that your app suddenly is supporting unlimited number of currencies.

**Comment by sal0max** [comment]
Do I understand correctly? You want be able to add custom currencies, with fixed user-defined rates?
There was already a request very similar to this, which I declined: #4 

However, your first use-case might be a valid point. I'll give it some time to think about it.

**Comment by sal0max** [comment]
This first use case of this request is pretty much solved with this feature: https://github.com/sal0max/currencies/issues/25
