### ISSUE TITLE
Rate request: Omani Rial (OMR)

### ISSUE THREAD

**Issue by magdesign** [sal0max/currencies#52]
any chance to add custom currency/rates?

missing Omani OMR

I know the troubles with the api's, so adding a custom currency somehow would be very nice!

**Comment by sal0max** [comment]
Regarding custom currency rates, there have been already similar issues, which I declined. See #5 and #4.

However, I will try to deal with your request by looking for an provider which provides rates for OMR.

**Comment by magdesign** [comment]
dont worry about me, already in another country with other currency, it was more a proposal for a new feature 😅

**Comment by sal0max** [comment]
Omani Rial rates are provided by OpenExchangerates API, which is included in the latest release 1.22.0. However, no timeline data for now.
