### ISSUE TITLE
[Feature Request] Open Exchange Rates data provider

### ISSUE THREAD

**Issue by lord-aerion** [sal0max/currencies#53]
With the loss of `exchangerate.host` the number of currencies supported by this amazing app has dropped considerably.

Would you consider adding support for [Open Exchange Rates](https://openexchangerates.org)? They offer a forever free plan that's limited to two API keys and 1,000 API calls a month, _more_ than adequate for the target audience of this app, i.e., casual travellers.

I appreciate this is more of an advanced feature since not everyone knows what an API is, but it's not exactly rocket science either. It is supported by at least two other apps on F-Droid: [My Expenses](https://f-droid.org/en/packages/org.totschnig.myexpenses/) and [STARGW FX](https://f-droid.org/en/packages/net.stargw.fx/), and both provide very basic instructions on what to do (essentially _register a free account on openexchangerates.org_ and _provide your API key/App ID here_).

It would greatly increase the amount of supported currencies (over 200), with the benefit of hourly updates.

**Comment by sal0max** [comment]
I tried to implement support for Open Exchange Rates. However, they heavily limit the usage of their [time series API](https://docs.openexchangerates.org/reference/time-series-json):

- > Time Series requests are currently available for clients on the Enterprise and Unlimited plans.
- > The maximum query period currently allowed is one month. If you need more than one month’s data, please request months sequentially
- > Please note that each day requested counts as one API request (so requesting a full month of data will count as up to 31 ‘hits’).

This will make it impossible to provide time series in this app. Do you have any suggestion how to remedy this situation?

**Comment by lord-aerion** [comment]
I'm afraid not. I just created a free account, and added the App ID (their term for API key) to the aforementioned apps. The free account states that it provides hourly updates and 1000 API calls a month.

That suggests that Time Series is something other than hourly updates.

**Comment by sal0max** [comment]
Yeah, the amount of API calls used for time series is one issue. But not being available to free users simply breaks it.

However I'm thinking about providing this API for regular usage anyway and simply showing a message that this API doesn't support time series. I guess it's a feature not heavily used.

The benefit of that wide range of exchange rates might be worth it.

**Comment by sal0max** [comment]
I've implemented this API. No support for timeline data, though. Users have to enter their own API Key.

Will arrive with the next release.

e0207d36e78c218c64dc0eb539d1427d5200de36

**Comment by sal0max** [comment]
v1.22.0 releases, which contains this feature.
