### ISSUE TITLE
Provide latest version 1.22.0 on Fdroid

### ISSUE THREAD

**Issue by CodeShakingSheep** [sal0max/currencies#56]
Fdroid is on version 1.15.0 from 2022, see https://f-droid.org/packages/de.salomax.currencies/. Somehow on my device I have version 1.21.1 installed. I don't know how this is possible as I installed it via Fdroid and never directly downloaded the APK.

When downloading the APK from GitHub I cannot install it as it conflicts with the Fdroid APK. Plus, I don't want to use the Playstore APK.

So, my request is that the version on Fdroid gets updated. Additionally could you also provide a non Playstore APK here on GitHub directly @sal0max?

Background of my request: The currency of the country I'm in is not provided. So, I want to check out version 1.22.0 newly introduced API and see if it provides the currency.

**Comment by sal0max** [comment]
Yeah.. F-Droid recently removed all newer builds from their store. You can read about the background here: #55

You may know, that APKs have to be signed and that signature can't change during app versions. That's the reason, you can't use the APK I uploaded to GitHub. And that is also the reason, I can't provide a build that's compatible with F-Droid, as they use their own secret signing key.

In issue #55 @licaon-kter promised to activate the latest version on F-Droid again, but I guess [that's still outstanding](https://gitlab.com/fdroid/fdroiddata/-/commits/93f7c460c3f372fed1be92532e76c0214f8140d4/metadata/de.salomax.currencies.yml).

To be honest: If you have access to the Play Store, you might think about switching to that version. The Play Store version of my app is as free as the F-Droid one. And [security experts tend to recommend to use the Play Store over F-Droid](https://privsec.dev/posts/android/f-droid-security-issues/). But ultimately, it's your own decision. I will try my best to continue to provide F-Droid builds of my app, but as you see, it's not fully in my own hand.

**Comment by licaon-kter** [comment]
It's coming soon, yes :)

**Comment by sal0max** [comment]
> > And security experts tend to recommend to use the Play Store over F-Droid
> 
> Wait, who? :) :) :)

😄 It would be strange for you to not have a different opinion.

Don't get me wrong: I love the idea of F-Droid app store and will try to continue to provide my app there, as best as I can. However with my app, I can vouch for the Play Store version being as _good_ as the F-Droid one.

That's the beauty of Android: You have a choice!

**Comment by CodeShakingSheep** [comment]
Hi @sal0max,
Thanks for your fast reply and also thanks for this great simple app without tracking in general. 🙏 

I read through the link you provided about Fdroid security. Interesting and I understand the potential drawbacks. Thanks for sharing it. However, for now I prefer using the Fdroid app.

I just have two questions left:

1. How come I had version 1.21.1 installed when the latest version in Fdroid currently is 1.15.0? That's because the builds were present in the first place and then removed later because of the licensing issue, right? I uninstalled and reinstalled the app via Fdroid and now I'm on version 1.15.0 again 😄 But great news that the latest version will be available soon on Fdroid 🙌

2. Formally in this app there are absolutely no differences between Fdroid and Playstore APK? No additional Google dependencies or similar? If that's the case, why is the APK provided on GitHub named with "Playstore"? Just curious about it.

**Comment by licaon-kter** [comment]
1. Yes

**Comment by sal0max** [comment]
> 1. How come I had version 1.21.1 installed when the latest version in Fdroid currently is 1.15.0? That's because the builds were present in the first place and then removed later because of the licensing issue, right? I uninstalled and reinstalled the app via Fdroid and now I'm on version 1.15.0 again 😄 But great news that the latest version will be available soon on Fdroid 🙌

All version after 1.15.0 got removed from F-Droid because of licensing issues. They were removed only recently, so you got 1.21.1 via regular updates. And as licaon-kter already replied: 1.22.0 is compatible with F-Droid, again, and will be available shortly (F-Droid can take some days to provide a new version after the Github release).


> 2. Formally in this app there are absolutely no differences between Fdroid and Playstore APK? No additional Google dependencies or similar? If that's the case, why is the APK provided on GitHub named with "Playstore"? Just curious about it.

Yes, my app is 100% identical in terms of trackers (that is: none), dependencies, etc. Only one difference, to be precise: The F-Droid version has a link in the settings where you can donate money. Google doesn't allow that.

Regarding the APK upload in Github: As already mentioned, APKs have to be signed. And you can only update from one version to another, when the exact same signing key is used. F-Droid has its own signing key. If I'd provide the F-Droid version here on Github, I'd have to use my own signing key, making it incompatible with the F-Droid downloads. Hence, I upload only the Play Store version here, as it is compatible with the Play Store downloads (both signed by my own private signing key).

**Comment by sal0max** [comment]
1.22.0 is available on F-Droid.

Thank everyone for the participation with this issue.
