### ISSUE TITLE
clear all

### ISSUE THREAD

**Issue by saltsoftdrink** [sal0max/currencies#57]
Add a btn to clear all

**Comment by sal0max** [comment]
Just press the delete button for at least 1s.

That good enough?

**Comment by saltsoftdrink** [comment]
> Just press the delete button for at least 1s.
> 
> That good enough?

I just wanna click instead of holding

**Comment by sal0max** [comment]
> > Just press the delete button for at least 1s.
> > That good enough?
> 
> I just wanna click instead of holding

And I want well-formulated, purposeful feature requests, that describe a valid use case. I guess we're both out of luck. ✌️
