### ISSUE TITLE
CAD missing with Bank of Canada

### ISSUE THREAD

**Issue by any1th3r3** [sal0max/currencies#58]
First off, thank you for adding more exchange rate providers over the past few months!  
  
I've noticed that CAD was not available as a currency in conjunction with Bank of Canada, although exchange rates are initially provided in that currency.  
Since this doesn't appear to be an issue for Norges Bank / NOK, I assume something akin to [this](https://github.com/sal0max/currencies/blob/master/app/src/main/kotlin/de/salomax/currencies/model/adapter/NorgesBankRatesXmlParser.kt#L69) might be missing for Bank of Canada, but I could be mistaken.

**Comment by sal0max** [comment]
Good catch! Thank you!

Will publish an update, soon.
