### ISSUE TITLE
[Feature Request] add charts for historic rates

### ISSUE THREAD

**Issue by iNtEgraIR2021** [sal0max/currencies#9]
Hi 👋🏼 

in addition to [#8](https://github.com/sal0max/currencies/issues/8) I'd like to add that having **charts** displaying **historic rates** would be another great feature.

I also found the library [AAChartCore-Kotlin](https://github.com/AAChartModel/AAChartCore-Kotlin) googling for possible solutions.

To precise my proposal please see this working (web) app: <https://forexrate.web.app/>

I have to admit that I'm not a android dev myself so I can't estimate the time and effort needed to integrate this idea.

Looking forward to your answer. Greetings, Petra

**Comment by sal0max** [comment]
This is something I could imagine in the future. 👍

Both frankfurter.app and exchangerate.host provide time-series data.
* https://api.frankfurter.app/2021-01-01..?from=EUR&to=USD
* https://api.exchangerate.host/timeseries?start_date=2021-01-01&end_date=2022-01-01&base=EUR&symbols=USD

The behaviour of frankurter is already strange, as the first date in the response is not 2021-01-01, but 2021-01-04. That's 210 days difference, which is an odd number.

**This leads to my question:**
What time span would you propose for the historic rates? I'm thinking about maybe 1 year/month/week to choose from. However, at least 1 year doesn't seem possible with frankfurter.


Regarding chart libraries, there seem to be more than enough to choose from.
* https://github.com/diogobernardino/williamchart
* https://github.com/robinhood/spark
* https://github.com/AAChartModel/AAChartCore-Kotlin
* https://github.com/PhilJay/MPAndroidChart
* ...

**Comment by iNtEgraIR2021** [comment]
> 1 year/month/week

sounds great to me 👍🏼

**Comment by sal0max** [comment]
Implemented with 6f6e04f4723592b16887c672238d9f9f83830062

Will test it some time before releasing it, especially if the UI could be improved some more.
Here's how it currently looks like:
![Screenshot_1630109201](https://user-images.githubusercontent.com/423373/131199685-9b89551a-fc76-4e3f-9ce9-920b7d00946e.png)

**Comment by iNtEgraIR2021** [comment]
My first impression: looks great!

The section containing the avg, min and max looks a bit packed but this just a small and rather low-prio issue based on personal thoughts.

Again: the overall appearance is great!

Looking forward to a future release!

**Comment by sal0max** [comment]
I tweaked it a little more, the last couple two weeks and just released the new version. Should arrive in F-Droid and Google Play shortly.

<img src="https://raw.githubusercontent.com/sal0max/currencies/3edfc649df189c7367e583304a3b225ba85367f2/art/screenshots/screen03.png" width=450 />
